### ISSUE TITLE
Tibble error

### ISSUE THREAD

**Issue by littlehifive** [Global-TIES-for-Children/rcoder#2]
There is an incomprehensive `tibble` error when running `coding`. This went away when I updated the `tibble` package, but it might be worth flagging. The original issue was solved [https://github.com/tidyverse/tibble/issues/798](here). 
`Warning message:
`...` is not empty.

We detected these problematic arguments:
* `needs_dots`

These dots only exist to allow future extensions and should be empty.
Did you misspecify an argument? `

**Comment by psanker** [comment]
Yep! I ran into that as well. Might put a tibble >= 3.0.3 requirement in the package description.

**Comment by psanker** [comment]
Addressed in ed611fc8bce88a6b71a6599d14c3f96b7749ce3f
